// ballotsActions

export const BALLOTS_GET_BALLOT = 'BALLOTS_GET_BALLOT'
export const BALLOTS_GET_BALLOT_ERROR = 'BALLOTS_GET_BALLOT_ERROR'
export const BALLOTS_GET_BALLOT_SUCCESS = 'BALLOTS_GET_BALLOT_SUCCESS'

// bountiesActions

export const BOUNTIES_CLAIM_BOUNTY = 'BOUNTIES_CLAIM_BOUNTY'
export const BOUNTIES_CLAIM_BOUNTY_ERROR = 'BOUNTIES_CLAIM_BOUNTY_ERROR'
export const BOUNTIES_CLAIM_BOUNTY_SUCCESS = 'BOUNTIES_CLAIM_BOUNTY_SUCCESS'

export const BOUNTIES_GET_BOUNTY = 'BOUNTIES_GET_BOUNTY'
export const BOUNTIES_GET_BOUNTY_ERROR = 'BOUNTIES_GET_BOUNTY_ERROR'
export const BOUNTIES_GET_BOUNTY_SUCCESS = 'BOUNTIES_GET_BOUNTY_SUCCESS'

export const BOUNTIES_SUBMIT_WORK = 'BOUNTIES_SUBMIT_WORK'
export const BOUNTIES_SUBMIT_WORK_ERROR = 'BOUNTIES_SUBMIT_WORK_ERROR'
export const BOUNTIES_SUBMIT_WORK_SUCCESS = 'BOUNTIES_SUBMIT_WORK_SUCCESS'

// organizationActions

export const ORGANIZATION_CREATE_BALLOT = 'ORGANIZATION_CREATE_BALLOT'
export const ORGANIZATION_CREATE_BALLOT_ERROR = 'ORGANIZATION_CREATE_BALLOT_ERROR'
export const ORGANIZATION_CREATE_BALLOT_SUCCESS = 'ORGANIZATION_CREATE_BALLOT_SUCCESS'

export const ORGANIZATION_CREATE_BOUNTY = 'ORGANIZATION_CREATE_BOUNTY'
export const ORGANIZATION_CREATE_BOUNTY_ERROR = 'ORGANIZATION_CREATE_BOUNTY_ERROR'
export const ORGANIZATION_CREATE_BOUNTY_SUCCESS = 'ORGANIZATION_CREATE_BOUNTY_SUCCESS'

export const ORGANIZATION_CREATE_PROJECT = 'ORGANIZATION_CREATE_PROJECT'
export const ORGANIZATION_CREATE_PROJECT_ERROR = 'ORGANIZATION_CREATE_PROJECT_ERROR'
export const ORGANIZATION_CREATE_PROJECT_SUCCESS = 'ORGANIZATION_CREATE_PROJECT_SUCCESS'

export const ORGANIZATION_DELETE_BOUNTY = 'ORGANIZATION_DELETE_BOUNTY'
export const ORGANIZATION_DELETE_BOUNTY_ERROR = 'ORGANIZATION_DELETE_BOUNTY_ERROR'
export const ORGANIZATION_DELETE_BOUNTY_SUCCESS = 'ORGANIZATION_DELETE_BOUNTY_SUCCESS'

export const ORGANIZATION_DELETE_BALLOT = 'ORGANIZATION_DELETE_BALLOT'
export const ORGANIZATION_DELETE_BALLOT_ERROR = 'ORGANIZATION_DELETE_BALLOT_ERROR'
export const ORGANIZATION_DELETE_BALLOT_SUCCESS = 'ORGANIZATION_DELETE_BALLOT_SUCCESS'

export const ORGANIZATION_DELETE_PROJECT = 'ORGANIZATION_DELETE_PROJECT'
export const ORGANIZATION_DELETE_PROJECT_ERROR = 'ORGANIZATION_DELETE_PROJECT_ERROR'
export const ORGANIZATION_DELETE_PROJECT_SUCCESS = 'ORGANIZATION_DELETE_PROJECT_SUCCESS'

export const ORGANIZATION_GET_ACCOUNT = 'ORGANIZATION_GET_ACCOUNT'
export const ORGANIZATION_GET_ACCOUNT_ERROR = 'ORGANIZATION_GET_ACCOUNT_ERROR'
export const ORGANIZATION_GET_ACCOUNT_SUCCESS = 'ORGANIZATION_GET_ACCOUNT_SUCCESS'

export const ORGANIZATION_GET_CONTRIBUTOR = 'ORGANIZATION_GET_CONTRIBUTOR'
export const ORGANIZATION_GET_CONTRIBUTOR_ERROR = 'ORGANIZATION_GET_CONTRIBUTOR_ERROR'
export const ORGANIZATION_GET_CONTRIBUTOR_SUCCESS = 'ORGANIZATION_GET_CONTRIBUTOR_SUCCESS'

export const ORGANIZATION_GET_ORGANIZATION = 'ORGANIZATION_GET_ORGANIZATION'
export const ORGANIZATION_GET_ORGANIZATION_ERROR = 'ORGANIZATION_GET_ORGANIZATION_ERROR'
export const ORGANIZATION_GET_ORGANIZATION_SUCCESS = 'ORGANIZATION_GET_ORGANIZATION_SUCCESS'

export const ORGANIZATION_GET_TRANSACTIONS = 'ORGANIZATION_GET_TRANSACTIONS'
export const ORGANIZATION_GET_TRANSACTIONS_ERROR = 'ORGANIZATION_GET_TRANSACTIONS_ERROR'
export const ORGANIZATION_GET_TRANSACTIONS_SUCCESS = 'ORGANIZATION_GET_TRANSACTIONS_SUCCESS'

export const ORGANIZATION_RESET_ORGANIZATION = 'ORGANIZATION_RESET_ORGANIZATION'

// projectsActions

export const PROJECTS_GET_PROJECT = 'PROJECTS_GET_PROJECT'
export const PROJECTS_GET_PROJECT_ERROR = 'PROJECTS_GET_PROJECT_ERROR'
export const PROJECTS_GET_PROJECT_SUCCESS = 'PROJECTS_GET_PROJECT_SUCCESS'

// organizationsActions

export const ORGANIZATIONS_CREATE_ORGANIZATION = 'ORGANIZATIONS_CREATE_ORGANIZATION'
export const ORGANIZATIONS_CREATE_ORGANIZATION_ERROR = 'ORGANIZATIONS_CREATE_ORGANIZATION_ERROR'
export const ORGANIZATIONS_CREATE_ORGANIZATION_SUCCESS = 'ORGANIZATIONS_CREATE_ORGANIZATION_SUCCESS'

export const ORGANIZATIONS_DELETE_ORGANIZATION = 'ORGANIZATIONS_DELETE_ORGANIZATION'
export const ORGANIZATIONS_DELETE_ORGANIZATION_ERROR = 'ORGANIZATIONS_DELETE_ORGANIZATION_ERROR'
export const ORGANIZATIONS_DELETE_ORGANIZATION_SUCCESS = 'ORGANIZATIONS_DELETE_ORGANIZATION_SUCCESS'

export const ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR = 'ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR'
export const ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR_ERROR = 'ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR_ERROR'
export const ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR_SUCCESS = 'ORGANIZATIONS_GET_ORGANIZATIONS_CONTRIBUTOR_SUCCESS'

export const ORGANIZATIONS_GET_ORGANIZATIONS_OWNER = 'ORGANIZATIONS_GET_ORGANIZATIONS_OWNER'
export const ORGANIZATIONS_GET_ORGANIZATIONS_OWNER_ERROR = 'ORGANIZATIONS_GET_ORGANIZATIONS_OWNER_ERROR'
export const ORGANIZATIONS_GET_ORGANIZATIONS_OWNER_SUCCESS = 'ORGANIZATIONS_GET_ORGANIZATIONS_OWNER_SUCCESS'

export const ORGANIZATIONS_GET_ORGANIZATIONS = 'ORGANIZATIONS_GET_ORGANIZATIONS'
export const ORGANIZATIONS_GET_ORGANIZATIONS_ERROR = 'ORGANIZATIONS_GET_ORGANIZATIONS_ERROR'
export const ORGANIZATIONS_GET_ORGANIZATIONS_SUCCESS = 'ORGANIZATIONS_GET_ORGANIZATIONS_SUCCESS'

export const ORGANIZATIONS_GET_OWNER = 'ORGANIZATIONS_GET_OWNER'
export const ORGANIZATIONS_GET_OWNER_ERROR = 'ORGANIZATIONS_GET_OWNER_ERROR'
export const ORGANIZATIONS_GET_OWNER_SUCCESS = 'ORGANIZATIONS_GET_OWNER_SUCCESS'
