// factoryActions

export const FACTORY_CREATE_ORGANIZATION = 'FACTORY_CREATE_ORGANIZATION'
export const FACTORY_CREATE_ORGANIZATION_ERROR = 'FACTORY_CREATE_ORGANIZATION_ERROR'
export const FACTORY_CREATE_ORGANIZATION_SUCCESS = 'FACTORY_CREATE_ORGANIZATION_SUCCESS'

export const FACTORY_GET_ORGANIZATIONS = 'FACTORY_GET_ORGANIZATIONS'
export const FACTORY_GET_ORGANIZATIONS_ERROR = 'FACTORY_GET_ORGANIZATIONS_ERROR'
export const FACTORY_GET_ORGANIZATIONS_SUCCESS = 'FACTORY_GET_ORGANIZATIONS_SUCCESS'

// organizationActions

export const ORGANIZATION_GET_ORGANIZATION = 'ORGANIZATION_GET_ORGANIZATION'
export const ORGANIZATION_GET_ORGANIZATION_ERROR = 'ORGANIZATION_GET_ORGANIZATION_ERROR'
export const ORGANIZATION_GET_ORGANIZATION_SUCCESS = 'ORGANIZATION_GET_ORGANIZATION_SUCCESS'

export const ORGANIZATION_RESET_ORGANIZATION = 'ORGANIZATION_RESET_ORGANIZATION'
export const ORGANIZATION_SET_ORGANIZATION = 'ORGANIZATION_SET_ORGANIZATION'

// userActions

export const USER_GET_ACCOUNT = 'USER_GET_ACCOUNT'
export const USER_GET_ACCOUNT_ERROR = 'USER_GET_ACCOUNT_ERROR'
export const USER_GET_ACCOUNT_SUCCESS = 'USER_GET_ACCOUNT_SUCCESS'
